
* Electorate-Vanadium-Ledger
  :PROPERTIES:
  :CUSTOM_ID: electorate-vanadium-ledger
  :END:
Electorate is the ElectOS (https://electos.org) subsystem for voter
records management. Electorate Vanadium is the data warehouse for voter
records data and related data on a distributed digital ledger.
Electorate Vanadium Core presents a Web services API for clients to
access the data warehouse. Electorate Vanadium Ledger is the underlying
data storage for the warehouse, implementing the actual distributed
digital ledger.

The Vanadium Ledger's implementation is centered on the use of Amazon
Managed Blockchain. As a result, much of the software in this repository
is deployment automation for setting up a ledger. The
application-specific software is limited to lambda-function software
that works with an API Gateway to implement a serverless entry point to
the underlying ledger. This software, the Vanadium Agent, wraps the
ledger as a single point of access control decisions about which
software has the privilege to access the ledger. Curently, the design
supports the Electorate Vanadium Core as the sole component with that
access.
